print('INFORMAȚII PERSONALE\n')
print('\tNume Prenumne: Moglan Elena')
print('\tAdresă: Suceava 7, MD-3129, mun. Bălți, Republica Moldova')
print('\tTelefon: 37379007304 | Fax: 37323167394')
print('\tE-mail: moglan.elena@gmail.com')
print('\tSexul: feminin | Data nașterii: 27/11/2004 | Naționalitatea: moldoveancă | Statut: celibatar\n')
print('EDUCAŢIE ŞI FORMARE\n')
print('\t2011 - prezent     Instituția Publică Liceul Teoretic “Mihai Eminescu”, mun. Bălți')
print('\t2015 - 2018        Cursul de robotică, Instituția Publică Liceul Teoretic “Mihai Eminescu”, mun. Bălți')
print('\t2013 - 2018        Școala Sportivă Nr. 2, mun. Bălți, Secția de șah')
print('\t2006 - 2011        Grădinița Nr. 43 “Zâmbet”\n')
print('APTITUDINI ȘI COMPETENΤE PERSONALE\n')
print('\tLimba maternă:	    Româna\n')
print('\tAlte limbi străine cunoscute:\t\tScriere\t\tVorbire\t\tCitire')
print('\t  Engleza\t\t\t\t  B2\t\t  B2\t\t  B2')
print('\t  Germana\t\t\t\t  A2\t\t  A2\t\t  A2')
print('\t  Rusa\t\t\t\t\t  A1\t\t  A2\t\t  A2\n')
print('\tAptitudini și competențe artistice:')
print('\t ▪ brodare') 
print('\t ▪ croșetare') 
print('\t ▪ pictură\n')
print('\tAptitudini și competențe sociale:')
print('\t ▪ empatie')
print('\t ▪ amabilitate')
print('\t ▪ responsabilitate')
print('\t ▪ receptivitate')
print('\t ▪ cooperare\n')
print('\tAptitudini și competențe organizatorice:')
print('\t ▪ preocupare pentru rezultat')
print('\t ▪ răbdare')
print('\t ▪ proactivitate')
print('\t ▪ spirit de evaluare și îmbunătățire\n')
print('\tAptitudini și competențe tehnice:')
print('\t ▪ o bună cunoaștere a instrumentelor Microsoft Office™')
print('\t ▪ o bună cunoaștere a programării roboților de tip Lego\n')
print('INFORMAΤII SUPLIMENTARE\n')
print('\tParticipări în proiecte naționale și internaționale:')
print('\t ▪ Hippo “English Without Borders” Competition 2019')
print('\t ▪ The World’s Scholar Cup Regional Round 2019')
